use_frameworks!

platform :ios, '8.0'

target 'Component1_Example' do
  pod 'Component1', :path => '../'

  target 'Component1_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
